name: tasknest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 5.5.0
  cupertino_icons: ^1.0.8
  firebase_core: 3.11.0
  firebase_storage: 12.3.7
  carousel_slider: ^5.0.0
  firebase_auth: 5.3.4
  smooth_page_indicator: ^1.2.0+3
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_email_sender: ^7.0.0
  cloud_functions: ^5.3.2
  get: ^4.7.2
  flutter_animate: ^4.5.2
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.1
  geolocator: ^10.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon2.png"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/new.png
   - assets/image1.png
   - assets/image2.png
   - assets/image3.png
   - assets/image4.png
   - assets/image5.png
   - assets/image6.png
   - assets/image7.png
   - assets/image8.png
   - assets/image9.png
   - assets/image10.png 
   - assets/image11.png 
   - assets/image12.png 
   - assets/sdimage1.png
   - assets/sdimage2.png
   - assets/sdimage3.png
   - assets/logo.png
   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For example:
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

    - family: ILoveChristmas
      fonts:
        - asset: fonts/I Love Christmas.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
